= ratpack-kotlin-dsl

This is a dsl that aims to provide for kotlin developers what the ratpack groovy dsl provides for groovy developers.
See the https://ratpack.io/manual/current/groovy.html[ratpack groovy docs] for details.

== Main Application

=== Via kscript

Install kscript
```
sdk install kotlin
sdk install kscript
```

Create your api in a file called `ratpack.kts` or whatever you want
```
#!/usr/bin/env kscript
@file:CompilerOpts("-jvm-target 1.8")
@file:DependsOn("me.drmaas:ratpack-kotlin-dsl:1.3.0")
import ratpack.kotlin.handling.ratpack
ratpack {
  handlers {
    get { render("Hello World") }
  }
}
```

Run your api
```
./ratpack.kts
```

Test your api
```
curl localhost:5050
```

=== Via Kotlin Ratpack Script

Create src/ratpack/ratpack.kts
```kotlin
import ratpack.kotlin.handling.ratpack

ratpack {
  serverConfig {
    development(true)
    port(9000)
  }
  bindings {
    bindInstance("foobar")
  }
  handlers {
    get("test") {
      render("hello " + context.get<String>())
    }
  }
}
```

Create build.gradle.kts
```
plugins {
  id("me.drmaas.ratpack-kotlin") version "1.3.0"
  id("com.github.johnrengelman.shadow") version "2.0.2"
}

repositories {
  mavenLocal()
  jcenter()
}

dependencies {
  runtime("ch.qos.logback:logback-classic:1.2.3")
}

group = "com.example"
version = "0.0.1"
```

Run gradle
```
gradle run
```

Or build a jar and run
```
gradle shadowJar
java -jar build/libs/your-app-all.jar
```

then
```
curl localhost:9000/test
```

=== Via Main Method

Create a main class
```kotlin
fun main(args: Array<String>) {
  ratpack {
    serverConfig {
      development(true)
      port(9000)
    }
    bindings {
      bindInstance("foobar")
    }
    handlers {
      get("test") {
        render("hello " + context.get(String::class.java))
      }
    }
  }
}
```

Create build.gradle
```
... some gradle goes goes ...
```

Run gradle
```
gradle run
```

then
```
curl localhost:9000/test
```

== Handler Chain

```kotlin
class SampleChain : KChainAction() {
  override fun execute() {
    get("test") {
      render("hello")
    }
  }
}
```
```kotlin
fun main(args: Array<String>) {
  val app = ratpack {
    bindings {
      bind<SampleChain>()
    }
    handlers {
      prefix<SampleChain>("v1")
    }
  }
  `when`("a request is made") {
    val client = testHttpClient(app)
    val r = client.get("v1/test")
    then("it works") {
      r.statusCode shouldEqual 200
      r.body.text shouldEqual "hello"
      app.close()
    }
  }
}
```

== Enhanced DSL extensions using reified types

Additional Ratpack DSL extensions for Kotlin. This provides extension wrappers and extension methods for providing a
better Guice DSL experience from Kotlin. It takes advantage of reified types to reduce class references like
`bind(SampleChain::class.java)` to `bind<SampleChain>()`.
```
    ...
    bindings {
      bind<SampleChain>()
    }
    ...
```
or
```
    ...
    handlers {
      prefix<SampleChain>("v1")
    }
    ...
```
See all the available extension functions in `Extensions.kt`.

For additional Guice-specific extensions, see https://github.com/authzee/kotlin-guice.
